### ISSUE TITLE
Using d2-net in colmap

### ISSUE THREAD

**Issue by SkyRiderMike** [tsattler/visuallocalizationbenchmark#10]
I use my own data for testing d2-net in reconstruction.
I just follow the pipeline in the modify_database_with_custom_features_and_matches.py on my own dataset, and the match_list is generated using original sift matcher in colmap. And i get reconstruction result as follows:

the original sift result:(which has a perfect circle)
![image](https://user-images.githubusercontent.com/7625094/72198468-cf74c180-3468-11ea-9c76-f38023631a01.png)

and the d2-net result:(which don't have a perfect circle)
![image](https://user-images.githubusercontent.com/7625094/72198471-e61b1880-3468-11ea-9fab-0d5ce453ddf6.png)

the d2-net match seems quite noisy. And i simply follow the pipeline using match_importer and do the reconstruction.
![d2-net cvmatch](https://user-images.githubusercontent.com/7625094/72201687-b6ccd180-3491-11ea-9944-9d6265dc52de.png)

Then i try to add the ransc for the matches before import them into the colmap. However, the reconstruction results seems even worse: 
![image](https://user-images.githubusercontent.com/7625094/72201710-f85d7c80-3491-11ea-8f8b-57dded23baed.png)

All these methods share the same match_list. However, 
I found that original sift has better pose result than d2-net. Can you please give me some possible reasons for this ?

**Comment by tsattler** [comment]
D2-Net uses higher-level structures to identify and describe features. This is helpful if you want to match images taken under different seasons or illumination conditions as such features are more stable under such changes. The downside is that the features become less discriminative, i.e., D2-Net will match similar-looking structures even if they do not belong to the same physical structure. SIFT looks at low-level structures (gradients) and is much better at keeping similar-looking structures apart.

**Comment by SkyRiderMike** [comment]
> D2-Net uses higher-level structures to identify and describe features. This is helpful if you want to match images taken under different seasons or illumination conditions as such features are more stable under such changes. The downside is that the features become less discriminative, i.e., D2-Net will match similar-looking structures even if they do not belong to the same physical structure. SIFT looks at low-level structures (gradients) and is much better at keeping similar-looking structures apart.

Is that possible to use the sift keypoints and combine with the d2-net discriptors?

**Comment by tsattler** [comment]
Yes, you can do this, but you will need to do the matching yourself and import the features and matches into COLMAP.

**Comment by SkyRiderMike** [comment]
> Yes, you can do this, but you will need to do the matching yourself and import the features and matches into COLMAP.

Thanks! I’ll let you know if this way is working, thanks a lot
