### ISSUE TITLE
Why do the reference images have to be matched between themselves?

### ISSUE THREAD

**Issue by uzpaka** [tsattler/visuallocalizationbenchmark#11]
Hello, the 'image_pairs_to_match.txt' file contains pairs of query to reference (database) images, but also pairs of reference to reference images. When I remove the reference-to-reference pairs from the file, COLMAP fails to find 3D points and the poses of the query images. Why is that the case? Which pairs (query-to-reference or reference-to-reference) are used by COLMAP to find the 3D points? Shouldn't it be possible to triangulate 3D points by only having query-to-reference pairs of images?

Thank you and kind regards

**Comment by tsattler** [comment]
As mentioned in the README you can find in the subdirectory, the steps undertaken are:
The steps of the reconstruction pipeline are the following:
1. generate an empty reconstruction with the parameters of database images,
2. import the features into the database,
3. match the features and import the matches into the database,
4. geometrically verify the matches,
5. triangulate the database observations in the 3D model at fixed intrinsics,
6. register the query images at fixed intrinsics.
Step 5 uses the matches between the reference images to obtain the 3D points. Step 6 uses the matches between the queries and the reference images to obtain 2D-3D matches, which are then used to estimate the camera pose. Step 6 does not add new 3D points to the scene.

If there are no reference-reference matches, there are no 3D points, thus no 2D-3D matches, and thus no localized images.

It should be possible to obtain triangulations from query-reference matches, but this is not implemented in our scripts and I haven't figured out how to do this easily in Colmap without having to run the reconstruction from scratch.

**Comment by uzpaka** [comment]
Thank you for the clarification! My confusion came from how the 'colmap point_triangulator' function is implemented. At first I thought that it was also considering query images (since the query images and the query-ref matches are in the database that is given to this function). But, from what you just explained, 'point_triangulator' only considers registered images (i.e images which have a non-null pose I guess) for triangulating 3D points.

In your opinion, what would be the best way to generate 3D points from query-ref matches and use them to find/adjust the query poses (while having the reference poses given and fixed)? I am not sure what you meant by running the reconstruction from scratch. Does that mean that I should discard the given poses for the reference images and re-do the entire reconstruction as you described in your paper (Benchmarking 6DOF Outdoor Visual Localization in Changing Conditions)? Instead of this, what if I simply call 'point_triangulator' again after the 'image_registrator', since then the query images would be considered as 'registered'? I guess that colmap would have to refine both query and reference poses (during the bundle adjustment step of 'point_triangulator'), which is problematic since the reference poses should be fixed. 

We are currently working on improving local features (i.e increasing number of keypoint-matches) given a pair of images (and not just a single image). Since there are many more ref-ref pairs than query-ref pairs, our approach would be only reasonable (computationally) when applied to query-ref pairs.

**Comment by tsattler** [comment]
What I meant is this: I currently do not see an automated way such that Colmap automatically uses the matches between reference images that you get by transitivity from matches between the query and the reference images. This would be necessary to get 3D points triangulated from only query-reference matches if you want to use the fixed poses. 

What you could to is to manually compute transitive matches and then import them into Colmap. Once they are there, you can run triangulation from the reference images and then localize the query image.
I would expect this to work less well than directly matching the reference images for the reason that you will only get matches to the most similar reference images. If you also match reference images with each other, you will be able to build longer feature tracks, which should result in more accurately triangulated 3D points. These in turn should result in a more accurate camera pose estimate for the query.

Colmap allows to fix poses during bundle adjustment, so this fixing the reference poses is possible.

**Comment by tsattler** [comment]
Did this resolve the issue?

**Comment by uzpaka** [comment]
Yes, thank you.
