### ISSUE TITLE
Aachen model in COLMAP format

### ISSUE THREAD

**Issue by hyojinie** [tsattler/visuallocalizationbenchmark#12]
Hi! I was wondering if there is any future plan for releasing the 3D model from the Aachen Day-Night dataset in COLMAP binary or text formats.

**Comment by tsattler** [comment]
Hi! We currently don't have a COLMAP version of the Aachen Day-Night model that we released and making the COLMAP model that we have ready for release is a bit of work. At the moment, I don't have time to work on this.

I am not sure, but https://github.com/ethz-asl/hfnet might have a COLMAP model of Aachen.

**Comment by hyojinie** [comment]
Thank you, Torsten! I found this script: https://github.com/ethz-asl/hfnet/blob/b0400570cca78638ff97e8f2db2d2b1185abd0fd/colmap-helpers/example_scripts/run_aachen_sift.sh :)
