### ISSUE TITLE
The link to Cross-Seasons Correspondence dataset is broken

### ISSUE THREAD

**Issue by baiksung** [tsattler/visuallocalizationbenchmark#13]
Hi,

As the title says, the link to the dataset is broken. Could you update the link??

Thank you!

**Comment by maunzzz** [comment]
Hi baiksung!
Here is an updated link
https://www.dropbox.com/sh/ql8t2us433v8jej/AAAI52qWQUqs4LKUCbR1XLNWa?dl=0
Some info on data format an usage can be found in the repository for the corresponding paper
https://github.com/maunzzz/cross-season-segmentation

**Comment by tsattler** [comment]
Thanks @maunzzz
