### ISSUE TITLE
sqlite3.IntegrityError: UNIQUE constraint failed: matches.pair_id

### ISSUE THREAD

**Issue by Enderych** [tsattler/visuallocalizationbenchmark#15]
Hello,
during the 4th step of localization, I met an error like this:

python modify_database_with_custom_features_and_matches.py --dataset_path /data/d2-net/aachen --colmap_path /home/yang/Documents/Benchmark/colmap/build/src/exe --method_name d2-net --database_name d2-net.db --image_path images/images_upright/ --match_list retrieval_list.txt --matching_only True
Matching...
  0%|                                                                                                      | 0/1957 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "modify_database_with_custom_features_and_matches.py", line 189, in <module>
    match_features(images, paths, args)
  File "modify_database_with_custom_features_and_matches.py", line 137, in match_features
    (image_pair_id, matches.shape[0], matches.shape[1], matches_str))
sqlite3.IntegrityError: UNIQUE constraint failed: matches.pair_id

The reconstruction pipeline and the first 3 steps are OK. I tested with image_pairs_to_match.txt (including ref-ref and query-ref pairs) and retrieval_list.txt (only query-ref pairs), and it seems the image_pair_id is not unique, do you know how to solve this problem? Thank you.

**Comment by tsattler** [comment]
I never had this problem. How do you generate the retrieval_list.txt file?

**Comment by mihaidusmanu** [comment]
I have run into this issue before. In my case, the reason was either having duplicate image pairs in the matching lists or starting the reconstruction from a database which already contains matches.

**Comment by tsattler** [comment]
So far, I only ran into issues when there were already matches in the database. I think I always made sure that I do not have duplicate pairs.

**Comment by Enderych** [comment]
Thank you, I found that separate image_pairs_to_match.txt (14941 pairs) into database_pairs_list.txt (12984 pairs, only ref-ref) and retrieval_list.txt (1957 pairs, only night query-ref), use database_pairs_list.txt in step 2 and  retrieval_list.txt in step 4 solves the problem. So the matches id in steps 2 and 4 should not be duplicate.

But I am still confused since we already offer image_pairs_to_match.txt in 'reconstruction_pipeline.py'  so the ref-ref pairs and query-ref pairs are already known to the 'd2-net.db', right? Or does this reconstruction_pipeline.py only result in a sparse-d2-net-final document for us, with camera intrinsic and extrinsic, so the d2-net.db and  Aachen_eval_[d2-net].txt in this step should be ignored?

About the image_pairs_to_match.txt, I download it from your benchmark, I think you used NetVLAD to get top 20 candidates for each query and database image, am I right? But why does 4479 database images only have 12984 ref-ref pairs (4479 * 20 / 2 = 44790, '/2' means delete duplicate)? At the meantime, 103 night-query images only have 98 valid, and with 1957 (not 98 * 20 = 1960) query-ref pairs.

After I finished step 1 to 5 in 'Using COLMAP for Visual Localization with Custom Features', I use Colmap to do the database management and found that the extrinsic are all 'nan', so where is the final prediction of camera pose? Maybe in the images.bin document?

The last question is that could you please tell me how to get the nvm document like 'aachen_cvpr2018_db.nvm' for a new dataset after I use 'colmap automatic_reconstructor' for database images?

**Comment by tsattler** [comment]
Regarding your questions:
1. The repository offers two approaches to localization (explained in the "Usage" part, which explains how to use the code to participate in the local feature challenge of the CVPR 2019 workshop on Long-Term Localization, and in "Using COLMAP for Visual Localization with Custom Features", which explains how do build a general localization pipeline using COLMAP). In the first one, all image pairs for matching are read once. In the second part, first only database-database pairs are matched (step 2) and used for 3D reconstruction (step 3). Afterwards, query-database images are matched (step 4) and used for localization (step 5).

2. The data you downloaded was designed for the local feature challenge pipeline, not the localization pipeline. They were not generated by image retrieval but semi-manually. For details, please see Sec. 3.1 (Ground truth for night-time queries) in the CVPR 2018 paper describing the Aachen Day-Night dataset for details.

3. COLMAP does not store the extrinsics of the estimated poses in the database but in the generated 3D model. Please see COLMAP's documentation for details.

4. You can use COLMAP's model_converter functionality to generate nvm files from COLMAP reconstruction. Please see COLMAP's documentation.

**Comment by Enderych** [comment]
Thank you for your quick reply. 

1. Now I understand that in my situation, I need to build a general localization pipeline using COLMAP, so I have to separate the pairs into database-database and query-database images.

2. I think I have read this part but not totally understood. So maybe we can take this query-database pair data as ground truth for image retrieval methods like NetVLAD or DenseVLAD? If we need to do some ablation study of local feature relocalization (assume we have perfect image retrieval), we could take the query-database pairs directly as local feature matching candidates, is that right?

3.OK, do the 3D models means images.bin, cameras.bin and points3D.bin, and I need to transfer them to txt? If it is right, I think I could find a way to do it in COLMAP's documentation. But after that, I still need to test the accuracy of pose estimation by upload the result to your benchmark, or can I download the ground truth of query images' pose?

4. OK, I will try to use model_converter to transfer format from PLY to NVM.

Thanks a lot.

**Comment by tsattler** [comment]
Regarding your questions:
2. The query-database pairs are not ground truth. It is not guaranteed that all of the database images have sufficient visual overlap with the query image and there might be other database images that show the same part of the scene but are not in the list. The pairs are sufficient for the purpose of evaluating local features though (and thus correspond to the assumption that retrieval would give us good enough pairs to enable the feature matching and pose estimation stage).

3. You will need to submit your results to the evaluation server. We will not release ground truth poses.

**Comment by Enderych** [comment]
OK, I see, I have also found a few false-positive and false-negative pairs in/out the list. 
I have no more questions so far. Thank you very much.
