### ISSUE TITLE
Evaluation on RobotCar-Seasons: only “rear” matters?

### ISSUE THREAD

**Issue by dawnos** [tsattler/visuallocalizationbenchmark#17]
Hi! Thanks for your effects of hosting the benchmark.

I am trying to submit to the RobotCar-Seasons dataset. It is constituted of rear, left, and right. I found that if I set all “rear” as an invalid value (e.g. 1 0 0 0 for rotation and 10000000 0 0 for translation), I will get ALL 0s for the results (3 thresholds for day-all and night-all).

I am interested whether only the “rear” is used, or the rear is essential for evaluation.

Of course it is possible that my result for “left” and “right” is all incorrect.

So could you try to test the baseline method without the “rear” (set the lines of rear as invalid value)? Or anyone could me to try your method?

Thank you!

**Comment by tsattler** [comment]
Yes, only rear images are used for evaluation at the moment.

If you have poses for the left or right images, you can compute the poses of the rear images using the provided extrinsic calibration between the three cameras.

We are currently not planning to evaluate the left and right images and we will not release the ground truth poses for them as this would allow inferring the poses of the rear images.
