### ISSUE TITLE
Obtaining curves from original paper

### ISSUE THREAD

**Issue by hyenal** [tsattler/visuallocalizationbenchmark#18]
Hi, first of all thanks for the amazing code and for providing us  with the evaluation script!
I noticed in the original D2-Net paper ([https://arxiv.org/pdf/1905.03561.pdf](https://arxiv.org/pdf/1905.03561.pdf)) Figure 5 contains more extensive evaluations on the Aachen Day-Night.
Is there a way one could somehow obtain these curves ? 
I feel that this could be useful to have a more comprehensive evaluation.
Cheers,

**Comment by tsattler** [comment]
Hi, thanks for your interest. At the moment, we don't have this functionality publicly available. Offering it would mean updating the website to provide such curves.
We will discuss this.
