### ISSUE TITLE
RobotCar dataset in visual place recognition

### ISSUE THREAD

**Issue by mrgransky** [tsattler/visuallocalizationbenchmark#19]
Apologies in advance if this question is a bit off the context!

Given different categories of `RobotCar` dataset in folder `images` (i.e. dawn, dusk, night, etc) , I would like to apply AlexNet as a holistic feature extractor to retrieve top 5 images of database for a given query.

Let's say `overcast-reference` folder is my reference database containing `6954 * 3` images.
Given a query, for example from `night` folder containing `438 * 3` images, I do not know how ground truth should be defined to calculate correct matches.

How could one establish a image-to-image correspondences from reference to query to calculate `topX` matches?

To make my question clearer, here is an explanation for another dataset called `Nordland` which represent seasonal changes:

Given an `image Q` as qeury from Season `S1`, there is a matched `image R` in reference database in Seasons `S2`, `S3`, `S4`. 
Here is the ground truth distance matrix:
![gt](https://user-images.githubusercontent.com/11946010/81192574-190e8c80-8fc3-11ea-8991-7dff4ae424df.png)

Is there such an explanation for `RobotCar` dataset too?

Cheers,

**Comment by tsattler** [comment]
One motivation for our benchmark was for the camera poses for the test images to be not publicly available. As part of this, we are also not releasing lists of relevant reference images for each test image. If you need such lists, you will need to create them yourself.
