### ISSUE TITLE
"modify_database_with_custom_features_and_matches.py" with different dataset

### ISSUE THREAD

**Issue by zxp771** [tsattler/visuallocalizationbenchmark#20]
Thanks for your sharing and work
I'm wondering if I can use the "modify_database_with_custom_features_and_matches.py" with my own dataset.
I test your work with a few images(used COLMAP to generate the database.db and wrote the match_list.txt like the sample "visuallocalizationbenchmark/local_feature_evaluation/data/aachen-day-night/image_pairs_to_match.txt" you gave ) but get some errors below:
Cloud you give me some suggestion to modify the code?
Connected to pydev debugger (build 183.4886.43)
Importing features...
Matching...
0it [00:00, ?it/s]
  0%|          | 0/142 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/cv-group/pycharm-community-2018.3.2/helpers/pydev/pydevd.py", line 1741, in <module>
    main()
  File "/home/cv-group/pycharm-community-2018.3.2/helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/cv-group/pycharm-community-2018.3.2/helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/cv-group/pycharm-community-2018.3.2/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/cv-group/visuallocalizationbenchmark-master/local_feature_evaluation/modify_database_with_custom_features_and_matches.py", line 193, in <module>
    match_features(images, paths, args)
  File "/home/cv-group/visuallocalizationbenchmark-master/local_feature_evaluation/modify_database_with_custom_features_and_matches.py", line 125, in match_features
    image_id1, image_id2 = images[image_name1], images[image_name2]
KeyError: '1.jpg'

**Comment by zxp771** [comment]
PS: I think I misunderstanding with the function "image_ids_to_pair_id" and the variable "image_pair_id"

**Comment by tsattler** [comment]
It seems that there is no image called "1.jpg" in your database. Note that all filenames are relative to the directory containing the images (as specified to colmap).

**Comment by zxp771** [comment]
@tsattler Thanks for you reply
I organize all the data like below:
![image](https://user-images.githubusercontent.com/35118859/81804647-0c061600-954c-11ea-9aae-eb0941105b04.png)
and write the parameters on pycharm like this
![image](https://user-images.githubusercontent.com/35118859/81804846-67380880-954c-11ea-99a5-fb7736315477.png)
The imgs floder contained:
![image](https://user-images.githubusercontent.com/35118859/81805194-fc3b0180-954c-11ea-85ac-c02d83e58fe1.png)
The match_list contained:
![image](https://user-images.githubusercontent.com/35118859/81805260-1aa0fd00-954d-11ea-8c48-4555d17977a0.png)

**Comment by zxp771** [comment]
@tsattler 
I also confused by the function "image_ids_to_pair_id"?
What the purpose of the operation:“2147483647 * image_id2 + image_id1”？
Thanks for your help.

**Comment by tsattler** [comment]
When you created the database, did you set the image path to "imgs/"?

Image pair ids are stored as a single integer value. That is the purpose of the operation you mentioned. For more information, please have a look at the Colmap code.

**Comment by zxp771** [comment]
@tsattler 
BTW I generate the database.db by the colmap GUI.(just build a new project which contained the imgs folder shown on the figure I upload)

**Comment by tsattler** [comment]
So, is the image folder used in Colmap identical to "imgs/" or not?

**Comment by zxp771** [comment]
@tsattler 
Yes, I'm sure
![image](https://user-images.githubusercontent.com/35118859/81806084-8f286b80-954e-11ea-99de-a1a34581b5cd.png)

**Comment by tsattler** [comment]
Are you using the latest version from the repository? The errors shown above seem to be happening at positions where there is no code.

**Comment by zxp771** [comment]
@tsattler 
I just download this repository on Github yesterday. So I think it should be the latest version.
BTW I didn't understand what you said: "The errors shown above seem to be happening at positions where there is no code."
What do you mean "no code"?

**Comment by tsattler** [comment]
For example: This error `File "/home/cv-group/visuallocalizationbenchmark-master/local_feature_evaluation/modify_database_with_custom_features_and_matches.py", line 193, in
match_features(images, paths, args)` says that there is an error in line 193. However, the file only has 190 lines.

Similarly, the line indicated here: `File "/home/cv-group/visuallocalizationbenchmark-master/local_feature_evaluation/modify_database_with_custom_features_and_matches.py", line 125, in match_features image_id1, image_id2 = images[image_name1], images[image_name2]` is empty in the file on the master branch.

**Comment by zxp771** [comment]
Hi @tsattler 
I just checked the code.
I think these errors are not caused by the examples you mentioned.

**Comment by tsattler** [comment]
Looking at your error trace, the error is
`File "/home/cv-group/visuallocalizationbenchmark-master/local_feature_evaluation/modify_database_with_custom_features_and_matches.py", line 125, in match_features
image_id1, image_id2 = images[image_name1], images[image_name2]
KeyError: '1.jpg'`
The problem is that the program can't find the image `1.jpg` in the list of images in the database.

What is strange is that the error happens in a line that should be empty based on looking at the code in the master branch.

**Comment by zxp771** [comment]
@tsattler 
I download your code again but the errors still appear.
I'm wondering if I build the database.db from COLMAP with a wrong way.
I just use "new project" to create the db file like below:
![image](https://user-images.githubusercontent.com/35118859/81809631-3e1b7600-9554-11ea-891d-54a59dffaba5.png)
then chick the "save" to generate the database.db.]
Do I miss some steps?
I'm sure the imgs folder for this repository is the same as I used to generate the database.db

**Comment by tsattler** [comment]
If you are not extracting features, then the database will be empty and it can't find the image in the database.
Please read this in detail: https://github.com/tsattler/visuallocalizationbenchmark/tree/master/local_feature_evaluation#using-colmap-with-custom-features

**Comment by zxp771** [comment]
@tsattler 
Thanks for your reply
I prepared all the things as what you wrote on the website.
of course, I use the D2-net to extract the feature for all the images in imgs/ and put all of the .d2-net files into the imgs folder.
BTW I'm sure the code has read these feature and descriptor like below:
![image](https://user-images.githubusercontent.com/35118859/81878805-ae111700-95bb-11ea-8f39-946d9369641a.png)
BTW when I generate the database.db should I put all the .d2-net files into imgs folder or I need to put them into the imgs folder after generate the database.db?

**Comment by zxp771** [comment]
@tsattler 
Thanks for your help.
I think I find the step I missed.
