### ISSUE TITLE
output evaluation  results represent

### ISSUE THREAD

**Issue by fantuslk** [tsattler/visuallocalizationbenchmark#23]
IMG_20161227_173116.jpg 0.0676863 0.83592 -0.0595648 -0.541394 -329.917 120.202 655.417
IMG_20161227_191355.jpg 0.0435276 0.328245 0.0716575 0.940864 614.502 -91.751 -391.97
IMG_20161227_191118.jpg 0.0492746 0.572585 0.0497108 0.816852 346.767 -100.862 -638.47...
in the Aachen_eval_[].txt,what is the meaning of each  column?How can I get the similar results with the d2-net?

**Comment by tsattler** [comment]
Please have a look at the readme file provided with the Aachen dataset on the format of the output files.

I am not sure what you mean by the second part of the question. You can use the tools provided in this repository for localization with custom features such as D2-Net.
