### ISSUE TITLE
About aachen v1.1 and robotcar v2 dataset

### ISSUE THREAD

**Issue by kxhit** [tsattler/visuallocalizationbenchmark#27]
Hi! Thanks for making this wonderful benchmark.
I noticed that evluation on aachen v1.1 and robotcar v2 is available. However, I can't find the download link of these two datasets. Is it not ready yet? I'm confused. Hope you can help me. Thanks!

**Comment by tsattler** [comment]
We are currently preparing the datasets. We hope to make them available in the upcoming week.
