### ISSUE TITLE
Local feature challenge: unknown queries in Aachen database_v1_1.db

### ISSUE THREAD

**Issue by Skydes** [tsattler/visuallocalizationbenchmark#29]
**Problem:** Running `reconstruction_pipeline_aachen_v1_1.py` crashes since it attempts to [find missing features](https://github.com/tsattler/visuallocalizationbenchmark/blob/master/local_feature_evaluation/reconstruction_pipeline_aachen_v1_1.py#L155) for the following new queries:
```
query/night/nexus5x_additional_night/IMG_20170702_005615.jpg
query/night/nexus5x_additional_night/IMG_20170702_005557.jpg
query/night/nexus5x_additional_night/IMG_20170702_003519.jpg
query/night/nexus5x_additional_night/IMG_20170702_005427.jpg
query/night/nexus5x_additional_night/IMG_20170702_004734.jpg
```

**Reason:** The new database for Aachen v1.1 has 196 query images, so 98 new images, while `aachen_v1_1.zip` only contains 95 new queries in `images_upright/query/night/nexus5x_additional_night`.

**Quick fix:** Check that an image actually exists before importing its features.

**Better fix:** Cleanup `database_v1_1.db`.

**Comment by mihaidusmanu** [comment]
Can you try re-running the pipeline with this database and let me know if it works? https://drive.google.com/file/d/1VlF1HYvOTY2WudCdsBZ0ClZ_8VnU0I5c/view?usp=sharing

**Comment by Skydes** [comment]
Works fine now 👍

**Comment by tsattler** [comment]
@mihaidusmanu Thanks for your help! Could you upload the database to this repo?

**Comment by mihaidusmanu** [comment]
I just uploaded it - should be fine now!

**Comment by tsattler** [comment]
Thanks!
