### ISSUE TITLE
The upload results

### ISSUE THREAD

**Issue by shamangary** [tsattler/visuallocalizationbenchmark#3]
Hello. I want to ask about the uploaded results.
https://www.visuallocalization.net/benchmark/
For example, Aachen Day-Night dataset has day and night results.
Each of them has 3 different values.
However, the website does not specify what kind of evaluation metric is it.
I have to read d2-net paper and assume the values are
the percentage of correctly localized queries in different threshold: '0.5m, 2◦ 1.0m, 5◦ 5.0m, 10◦'.
Is this correct? I suggest that the website should directly specify the metric. Thanks.

**Comment by tsattler** [comment]
Dear @shamangary ,

the result correspond to the thresholds used in this paper: http://openaccess.thecvf.com/content_cvpr_2018/papers/Sattler_Benchmarking_6DOF_Outdoor_CVPR_2018_paper.pdf 

We will include the thresholds on the benchmark website, hopefully soon.

Best,
Torsten

**Comment by shamangary** [comment]
@tsattler Thank you very much!

**Comment by tsattler** [comment]
@shamangary The thresholds used for each dataset are now visible here: https://www.visuallocalization.net/benchmark/

**Comment by shamangary** [comment]
@tsattler Thank you for the prompt fix! Amazing benchmark!
