### ISSUE TITLE
RobotCar Seasons: inconsistent naming of queries

### ISSUE THREAD

**Issue by sarlinpe** [tsattler/visuallocalizationbenchmark#30]
In RobotCar Seasons, the database and query images have the extension `.jpg`, but are named as `.png` in the NVM and COLMAP models. In the submitted results, the evaluation server expects the queries to with end with `.jpg` for RobotCar v1, but with `.png` for RobotCar v2. This difference is not documented.

**Comment by tsattler** [comment]
Yes, this is an issue. We are working on this.

**Comment by tsattler** [comment]
This problem should be resolved by now. The server should convert file endings if necessary, i.e., it should not matter whether one submits .png or .jpg filenames.
