### ISSUE TITLE
How to get the day query intrinsics list for Aachen Day-Night v1.1 ? 

### ISSUE THREAD

**Issue by GabbySuwichaya** [tsattler/visuallocalizationbenchmark#32]
Hi @mihaidusmanu, thank you so much for the update and these great tools and datasets.
I have tried with the Aachen Day-Night V1.1.  I have seen the results for both day and night from some benchmark methods on https://www.visuallocalization.net/benchmark/. 

However, it seems that only the night queries' intrinsics are available in the package. 
I have downloaded the  [aachen_v1_1.zip](https://data.ciirc.cvut.cz/public/projects/2020VisualLocalization/Aachen-Day-Night) on the 27th of July.

Could you recommend how to get the day query intrinsics list for Aachen Day-Night v1.1? 

I  don't know how to get the list. Is it available at all?

**Comment by mihaidusmanu** [comment]
I think the intrinsics for the day queries remained the same as for Aachen Day-Night v1.0. They are available at https://data.ciirc.cvut.cz/public/projects/2020VisualLocalization/Aachen-Day-Night/queries/day_time_queries_with_intrinsics.txt. Maybe @tsattler can confirm.

**Comment by tsattler** [comment]
This question is answered in the readme file for the Aachen v1.1 dataset:
```
### Queries
We provide a text files with information about the intrinsics of all nighttime query images, both 
those of the original Aachen Day-Night dataset and the new nighttime queries.  The text file 
has the following file format: 
`image_name SIMPLE_RADIAL w h f cx cy r`
Here, `image_name` is the name of the query image. The name includes the subfolder names. 
The path of the image is relative to the `images_upright/` directory. The remainder of the 
line describes the intrinsic calibration of the camera. We use the `SIMPLE_RADIAL` model used 
in COLMAP (see [here](https://colmap.github.io/cameras.html) for details). 
The intrinsic calibration is defined by the width `w` and height `h` of the image, its focal length 
`f`, the position of the principal point (`cx` and `cy`), and a radial distortion parameter `r`. 
```
The text file with the intrinsics is in the queries/ sub-folder in the zip file that you downloaded.
