### ISSUE TITLE
Import SuperGlue feature matches

### ISSUE THREAD

**Issue by tudipffmgt** [tsattler/visuallocalizationbenchmark#36]
Since you already helped me once I will ask another question here - not strictly an issue ;).
I was able to import D2-net and R2D2 features into COLMAP using the provided scripts and then I calculated matches using the given matching methods.

Could I also use the script to import SuperGlue **inlier matches**? (https://github.com/magicleap/SuperGluePretrainedNetwork)
The workflow of SuperGlue directly provides matches from img_id1 to img_id2 in .npz file format.
My idea is to extract every feature point in every image and write it to a .superglue file format (the given .npz file format).

Since SuperGlue already provides inlier matches is it also possible to import inlier_matches with the modify_database_with_custom_features_and_matches.py?

**Comment by tsattler** [comment]
Yes, that should not be an issue. The mechanism for importing the matches is the same (writing the information into the Colmap database). I think this repository should actually have code for this: https://github.com/cvg/Hierarchical-Localization

**Comment by tudipffmgt** [comment]
Thanks! I already saw this repository few months ago but forgot about it. I will try using the reconstruction.py/triangulation.py there :)
