### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by rover-xingyu** [tsattler/visuallocalizationbenchmark#37]
I got "500 Internal Server Error" when I submit the results to the evaluation server.
Is there something wrong? Looking forward to your reply！

**Comment by CarlToft** [comment]
Hi Xingyu, 

Thank you for pointing this out. We are experiencing some technical issues at the moment, but we hope to have it resolved by tomorrow. 

Best regards,
Carl

**Comment by CarlToft** [comment]
Hi again Xingyu, 

Everything should be up and running again. Let me know if you run into any further issues! Closing the issue for now. 

Best regards, 
Carl

**Comment by rover-xingyu** [comment]
Thanks, it works again! @CarlToft
