### ISSUE TITLE
Signup problem : Server Error (500)

### ISSUE THREAD

**Issue by amaralibey** [tsattler/visuallocalizationbenchmark#40]
Hello,
I am trying to create an account on the website but I get this error after I click Register: Server Error (500)

**Comment by half-potato** [comment]
Did you crash the server lol. The entire website is down.

**Comment by amaralibey** [comment]
Hahaha, well it would be unfortunate to break the entire website after 3 or 4 attemps xD
But I guess the authors are maintaining it right now after I brought it to their attention ?

**Comment by tsattler** [comment]
We are looking into the issues. Thanks for notifying us.

**Comment by RoverXingyu** [comment]
Hi,
There is still a 502 Bad Gateway error in the server, am I miss something?

**Comment by tsattler** [comment]
We are still looking into why the server keeps freezing.

**Comment by tsattler** [comment]
Should be resolved now.

**Comment by LukasBures** [comment]
Sorry to bother you, @tsattler, but the server is down again with the same 502 code.

**Comment by tsattler** [comment]
Yes, we noticed. The issue seems to be that there are too many submissions for CMU Seasons that are evaluated in parallel, eating up the memory of the server. We are looking into this.
