### ISSUE TITLE
502 Bad Gateway Error again

### ISSUE THREAD

**Issue by rover-xingyu** [tsattler/visuallocalizationbenchmark#41]
Hi,
I got "502 Bad Gateway Error" today when I try to open the webpage of the benchmark.

**Comment by tsattler** [comment]
Yes, we are still working on it. It seems that whenever we get the website to work, something kills it.

**Comment by rover-xingyu** [comment]
Hi @tsattler 
Can we open the webpage again if we need the benchmark to record our result?

**Comment by tsattler** [comment]
We are working on resolving the issues that are causing the website to be down.

**Comment by rover-xingyu** [comment]
Thanks! Look forward to the restoration of the website as soon as possible. We need to use this data to complete our report tomorrow.

**Comment by tsattler** [comment]
We will try to have it up and running as soon as possible. However, we cannot guarantee that the website will be working again tomorrow as there seem to be issues with some submission to the CMU Seasons dataset.

**Comment by tsattler** [comment]
Should be working again now.
