### ISSUE TITLE
Why not add code keypoints[:, : 2] += 0.5?

### ISSUE THREAD

**Issue by rann1018** [tsattler/visuallocalizationbenchmark#42]
Hi,

I find this benchmark very useful for visual localization.
However, I notice that you do not add the code keypoints[:, : 2] += 0.5
to change keypoints position as other scripts such as local-feature-refinement.
Can you tell when I need to add code  keypoints[:, : 2] += 0.5?

Thanks a lot for your help.

**Comment by tsattler** [comment]
We are simply loading keypoints generated by some method from the disk. It is the responsibility of that method to provide accurate keypoint positions and we don't want to complicate things by adding some offset onto them.
