### ISSUE TITLE
The final results

### ISSUE THREAD

**Issue by Huang-NienPei** [tsattler/visuallocalizationbenchmark#43]
After I have done step 5, how do I get the percentage of correctly localized queries in different threshold: '0.5m, 2◦ 1.0m, 5◦ 5.0m, 10◦' ? 
Looking forward to your reply.
Thank you!

**Comment by tsattler** [comment]
Have you uploaded your results to visuallocalization.net?

**Comment by Huang-NienPei** [comment]
> Have you uploaded your results to visuallocalization.net?

I have converted the images.bin obtained in step 5 into images.txt, so should I upload the images.txt?

**Comment by tsattler** [comment]
No, the localization server cannot read the format of `images.txt` and the `images.txt` file will be too large to be handled by the server. You will need to extract the poses of the test images from `images.txt` and write them into the file format expected by visuallocalization.net (see the readme files of the individual datasets).

**Comment by Huang-NienPei** [comment]
> No, the localization server cannot read the format of `images.txt` and the `images.txt` file will be too large to be handled by the server. You will need to extract the poses of the test images from `images.txt` and write them into the file format expected by visuallocalization.net (see the readme files of the individual datasets).

Okay, I got it.
Thank you very much!
