### ISSUE TITLE
Upload results

### ISSUE THREAD

**Issue by Huang-NienPei** [tsattler/visuallocalizationbenchmark#44]
Hello, I would like to consult again about the results of step5. After I converted image.bin to image.txt, I found that the results were all poses of db images, which should be wrong. But I am not sure where the problem occurred, because I am experimenting in accordance with step1 to step5. What are the possible reasons for the results of db images?

Looking forward to your reply, thank you!

**Comment by tsattler** [comment]
Are you looking at the correct images.bin / images.txt file (the one in the folder with the results of `image_registrator`)?

What is the output of the registrator on the console? Does it state that it failed to localize images (e.g., due to a lack of feature matches)?

**Comment by Huang-NienPei** [comment]
1. The final result I used  is ''model_your_feature_name_with_queries/images.bin(images.txt)'' file.

2. After the operation of step5 is over, the terminal will display a result like this ‘‘Registering image #5426 (40)
========Image sees 0/107 points’’. 
<img width="327" alt="step5" src="https://user-images.githubusercontent.com/53600867/121152310-a8960700-c877-11eb-8dfd-29412ed534b5.png">

**Comment by tsattler** [comment]
I would recommend to have a look at the complete output on the terminal to see whether the same holds for the other query images. But it seems to me that you simply do not have enough correct matches to facilitate camera pose estimation.

**Comment by Huang-NienPei** [comment]
In step3, I changed the existing model used. 
I got this existing model through colmap for sparse reconstruction.

Finally, after step5 is over, images.bin is obtained. This images.bin contains database and query images. I extracted the query images information and converted it into the required format. After uploading it, the results (day and night) are all 0.0.

I'm not sure what the source of the error is. Could it be an error when colmap created the 3D model?


Attached is the document I uploaded.
[Aachen_eval_[d2-net].txt](https://github.com/tsattler/visuallocalizationbenchmark/files/6616160/Aachen_eval_.d2-net.txt)

**Comment by tsattler** [comment]
The evaluation server compares the poses in the submitted file with the reference poses stored on the server. These reference poses are in the coordinate frame of the provided 3D models. If you use your own 3D model and do not align it to the coordinate frame of the aligned 3D model, then you will end up with poses that do not match the reference poses. For example, the translational part of your poses is orders of magnitude off from the true values.

**Comment by Huang-NienPei** [comment]
If use the provided 3D models, does it mean that the 'db.db' in ‘‘--database_name db.db’’ is aachen.db [https://data.ciirc.cvut.cz/public/projects/2020VisualLocalization/Aachen-Day-Night/aachen.db](url) ?

**Comment by tsattler** [comment]
You can also scale your 3D model, use different features, etc. The important part is that the reference images have the same poses as those in the provided 3D model. Otherwise, sending your poses to the evaluation service does not make sense. 

I don't remember whether aachen.db contains all images of Aachen v1.1 or only those of the original images.

**Comment by Huang-NienPei** [comment]
Question one:
The existing model required by step 3 was obtained by using colmap in the following way:
1.extract features
2.match features
3.start reconstruction (sparse) [https://colmap.github.io/tutorial.html#sparse-reconstruction](url)
4.export all models
Is this method wrong? If it is correct, how can I scale the 3D model I get?

Question two:
I found that aachen.db includes query images of aachen v1.1.
But I don’t need v1.1 query images.I just need this [https://data.ciirc.cvut.cz/public/projects/2020VisualLocalization/Aachen-Day-Night/images/database_and_query_images.zip](url)
If I want to use aachen.db, can I directly delete the v1.1images information in aachen.db and use it?


Looking forward to your reply.

thank you very much!

**Comment by tsattler** [comment]
Regarding question 1:
The approach, if you scale the model (see the colmap documentation for information how to do this), is okay. However, the model that you get from the reconstruction will not be completely identical to the reference model. As such, the poses you submit will both contain the standard localization error / uncertainty and an alignment error.
A better approach is to retriangulate the scene from the known poses (which is essentially what the code in this repository does). See the colmap documentation for details.

Regarding question 2:
Aachen v1.1 also has new database / reference images, but you could simply ignore the new images and just use the old ones.
