### ISSUE TITLE
Local feature challenge

### ISSUE THREAD

**Issue by Huang-NienPei** [tsattler/visuallocalizationbenchmark#45]
This document [image_pairs_to_match.txt](https://github.com/tsattler/visuallocalizationbenchmark/blob/master/local_feature_evaluation/data/aachen-day-night/image_pairs_to_match.txt) only contains match pairs about nighttime. If I want to perform a ''Local feature challenge'' on daytime images, how do I get match_pair.txt about daytime images?

Looking forward to your reply
Thank you!

**Comment by tsattler** [comment]
The local feature challenge was part of a series of workshops that we organized. In the challenge, we focused on the nighttime images and thus there are no pairs for the daytime queries.

If you want to evaluate your features on all query images, I would suggest to use image retrieval to identify relevant database images for each query image. For this, you could use the Kapture toolbox (https://github.com/naver/kapture-localization). They might even already provide the relevant retrieval list for Aachen.
Note that this is not part of the definition of the local feature challenge we organized.
