### ISSUE TITLE
ORB descriptor 

### ISSUE THREAD

**Issue by Huang-NienPei** [tsattler/visuallocalizationbenchmark#47]
The type of ORB will be CV_8U as it is a binary descriptor.
It is also closely related to the type of norm to use for matching descriptors: NORM_HAMMING and its derived for binary descriptors.

In [matchers.py](https://github.com/tsattler/visuallocalizationbenchmark/blob/master/local_feature_evaluation/matchers.py) , I see L2 normalized descriptors, so does that mean I can't use ORB descriptors for this experiment?

Looking forward to your reply!
Thank you!

**Comment by tsattler** [comment]
The Hamming distance and the Euclidean distance between two unnormalized binary vectors are related, i.e., minimizing the Euclidean distance also minimizes the Hamming distance. You should not normalize the descriptors though.
Of course, you could also implement your own matcher.
