### ISSUE TITLE
About Aachen-day query

### ISSUE THREAD

**Issue by shamangary** [tsattler/visuallocalizationbenchmark#5]
Hello.

Is it possible to ask for the pair between day query and db images?
I notice that in 'image_pairs_to_match.txt' file, night query only corresponds to a few db images.
May I ask how do you determine the pair? (GPS? Global descriptor?)

BTW, is it too soon to ask for Robotcar and CMU evaluation code as well?

Thank you very much

-----------------
update:

For the 1st question, after I re-read the paper, the reason there is no day query is that it's too simple if the candidate is provided. Therefore, the benchmark encourage people to use global+local descriptors for the whole localization pipeline. Is this correct?

**Comment by tsattler** [comment]
Indeed, providing the most similar database image for each query would make the problem too simple. As such, we will not provide this information.

We are currently not planning to provided local feature evaluation code for RobotCar and CMU anytime soon as we are currently lacking the time to prepare them. At the same time, both datasets are considerably larger than Aachen and would take much longer to evaluate.
If you want to evaluate local features on RobotCar and CMY, you could use image retrieval (for example DenseVLAD or NetVLAD) to find relevant database images per query, then perform feature matching, and use COLMAP's feature_triangulator and image_registrator for localization.

**Comment by shamangary** [comment]
@tsattler Thank you very much :)
