### ISSUE TITLE
[RobotCar seasons V2] test image format

### ISSUE THREAD

**Issue by RuotongWANG** [tsattler/visuallocalizationbenchmark#50]
Hello. I have downloaded the RobotCar seasons V2 dataset from https://www.visuallocalization.net/ . The test image filenames provided by `robotcar_v2_test.txt` is in _.png_ format, while all images in the `images/` folder is in _.jpg_ format. Besides, the conditions is not specified in test image filenames. Is it a mistake or there are additional test image packages? 

Looking forward to your reply, thank you!

**Comment by tsattler** [comment]
There are no additional test images. It is just that originally, we used `png` files but released the images as `jpg` due to memory restrictions. We never updated the file names though.
