### ISSUE TITLE
Reconstruction pipeline issue

### ISSUE THREAD

**Issue by KunB-Fighting** [tsattler/visuallocalizationbenchmark#51]
Hi, 
I meet a similar problem with [issue#48](https://github.com/tsattler/visuallocalizationbenchmark/issues/48) 

part of the output:
```
==============================================================================
Triangulating image #4479 (4327)
==============================================================================

  => Image sees 0 / 0 points
  => Triangulated 0 points

==============================================================================
Retriangulation
==============================================================================

  => Completed observations: 0
  => Merged observations: 0

==============================================================================
Bundle adjustment
==============================================================================

F1014 12:30:37.116462 3119869 colmap.cc:1598] Check failed: bundle_adjuster.Solve(&reconstruction) 
*** Check failure stack trace: ***
    @     0x7f42e487e1c3  google::LogMessage::Fail()
    @     0x7f42e488325b  google::LogMessage::SendToLog()
    @     0x7f42e487debf  google::LogMessage::Flush()
    @     0x7f42e487e6ef  google::LogMessageFatal::~LogMessageFatal()
    @     0x5596554a035d  RunPointTriangulator()
    @     0x559655490e4a  main
    @     0x7f42e28240b3  __libc_start_main
    @     0x55965549aeee  _start
Aborted (core dumped)
```
what I have done:
check the matches in the database: I check the number of match pairs and the "data" in the matches table in the database, they are correct.

test with more features: I have test with 8k, 16k, 20k features per image, neither can work with pipeline v1

reconstruct with pipeline_v1.1: running the pipeline v1.1 with the same custom features (including 8k, 16k, 20k) is ok, and can reconstruct the scene then get the query poses

**Comment by tsattler** [comment]
Can you share the complete output / log?

**Comment by KunB-Fighting** [comment]
Thanks for the reply, and here is the complete output
[aachen_log.txt](https://github.com/tsattler/visuallocalizationbenchmark/files/7351542/aachen_log.txt)

**Comment by tsattler** [comment]
Looking at the output, there either seem to be no matches between the database images stored in the database or not enough of them. As a result, no 3D points get generated, which leads to the failure above.

**Comment by KunB-Fighting** [comment]
Emm, but the same features work with pipeline v1.1, I will check the matches in the database again, and maybe I will test with mutual nn matcher with a ratio test to filter the initial matches, I will leave this issue open and report latter, thanks!

**Comment by tsattler** [comment]
Can you be a bit more specific what you did and what works and what does not work?

**Comment by KunB-Fighting** [comment]
Yes, of course, but I am not sure what details can help.
I extract and save the features for the entire aachen-day-night dataset, then these features can work with pipeline v1.1 as well as hloc (test with netvlad50) but failed with pipeline v1.
As you can see, the pipeline v1 failed to triangulate points, however, the pipeline v1.1 succeed, and I have checked the sparse model made by v1.1 with colmap gui, the model makes sense.
At the beginning in the log, I have output the raw matches (which is generated by the nn matcher), there are more than 2k matches for every pairs, now I think it may be because there are too many noise in the raw matches and leads to a bad initial pair selection for reconstruction. I will try to use nn matcher with a ratio test then.

**Comment by tsattler** [comment]
What do you mean by `pipeline v1` and `pipeline v1.1`? Are these different reconstrunction / localization pipelines? If yes, what is the difference?

**Comment by KunB-Fighting** [comment]
Yours pipeline for aachen-day-night v1.1 in [/local_feature_evaluation/reconstruction_pipeline_aachen_v1_1.py](https://github.com/tsattler/visuallocalizationbenchmark/blob/master/local_feature_evaluation/reconstruction_pipeline_aachen_v1_1.py), the features can work with it. But the features can not work with [local_feature_evaluation/reconstruction_pipeline.py](https://github.com/tsattler/visuallocalizationbenchmark/blob/master/local_feature_evaluation/reconstruction_pipeline.py)

**Comment by KunB-Fighting** [comment]
The differences are the image-match-list and the database, since you provide another match list with more match pairs for aachen-day-night v1.1 and add more database images.

**Comment by KunB-Fighting** [comment]
I am sorry, it is my fault, I use the wrong image match list which only contains the pairs about query images, and therefore the reconstruction cannot work. Now I replace the match list with the latest one in this repository, and it works

**Comment by Frank-Dg** [comment]
hi，I replace the match list with the latest one in this repository, but  it did not work

**Comment by Frank-Dg** [comment]
@KunB-Fighting
