### ISSUE TITLE
What kind of data form do I need in COLMAP?

### ISSUE THREAD

**Issue by annee23** [tsattler/visuallocalizationbenchmark#52]
Hello I am trying to use the code,
but I have issue on using COLMAP.
Do I have to use db format? or exe format?
Can you describe little bit more about this part please,,,

Thank you for your clear codes.

**Comment by tsattler** [comment]
Colmap stores all the information it needs in a database. Without it, it cannot run. Our code runs Colmap by calling its executable. It should be possible to write custom C++ code that links against Colmap as a library to do all the operations, but the effort required to implement it does not seem to be justified compared to the benefits.

Does this answer your questions?

**Comment by annee23** [comment]
Then if you say so, do I have to write the address of where exe file is? There was a permission error accused when I tried so,,, Is there any way not to using colmap to evaluate in  Aachen day-night dataset? Thank you again for your fast reply.

**Comment by tsattler** [comment]
Yes, you need to specify the directory where the Colmap executable is located. This is done by passing the directory as a parameter to the python code contained in this repository.
Our pipeline uses Colmap to do pose estimation, re-triangulation, etc. You can of course implement these steps without Colmap.
