### ISSUE TITLE
SILDa Weather and Time of Day Dataset link broken

### ISSUE THREAD

**Issue by mrgransky** [tsattler/visuallocalizationbenchmark#57]
The link for SILDa Weather and Time of Day Dataset seems to be broken!
![bild](https://user-images.githubusercontent.com/11946010/154977483-42291d16-b232-4e8a-881b-98fdcc800e2a.png)

Is there any alternative link?
Cheers,

**Comment by tsattler** [comment]
The dataset is available via kapture (https://github.com/naver/kapture).
