### ISSUE TITLE
Link Broken: DenseVLAD

### ISSUE THREAD

**Issue by MubarizZaffar** [tsattler/visuallocalizationbenchmark#58]
Thank you for this very useful repository.

The link to DenseVLAD as reported here: http://www.ok.ctrl.titech.ac.jp/~torii/project/247/ is broken. Is it possible to update it with a recent working link? Many thanks.

Regards
Mubariz

**Comment by tsattler** [comment]
To the best of my knowledge, the webpage is currently down due to server problems. I'd expect it to become available again.
We are currently also looking into alternative hosting options.
