### ISSUE TITLE
Robotcar single condition submit

### ISSUE THREAD

**Issue by slz929** [tsattler/visuallocalizationbenchmark#59]
Thanks for the amaing benchmark construction!
I wonder how the metrics on the website are calculated when the poses of only one condition like ['sun'] ?  
Is that value are averaged by all conditions in 'day all'? 
And also 'rear' 'left' 'right' all used for evaluation?

Because all condition are squeesed into 'day all'.

Thanks.

**Comment by tsattler** [comment]
Thanks for your kind words.

Only the 'rear' images are used for evaluation. For each condition, metrics are calculated separately and you can see the results by clicking on a submission (e.g., https://www.visuallocalization.net/details/12756/). 'day all' is considered as a condition as well that contains all images taken during daytime. As such, the metrics are calculated over all daytime images and not averaged over other conditions.
