### ISSUE TITLE
Server Error when creating an account

### ISSUE THREAD

**Issue by fdarmon** [tsattler/visuallocalizationbenchmark#6]
Hi, I have a server error 500 when I try to create an account. Is it a bug or have you stopped the online evaluation now that CVPR2019 is over ?

Thanks

**Comment by tsattler** [comment]
@fdarmon Thank you very much for letting us know. We plan to keep the server up and running for the foreseeable future.

We will look into what is going wrong there.

**Comment by CarlToft** [comment]
Hi @fdarmon, the problem should be resolved now. Please let us know if you are still experiencing issues with the sign up process.

Regards,
Carl Toft

**Comment by fdarmon** [comment]
@CarlToft thanks, it works now

**Comment by rover-xingyu** [comment]
> Hi @fdarmon, the problem should be resolved now. Please let us know if you are still experiencing issues with the sign up process.
> 
> Regards,
> Carl Toft

Hi! @CarlToft  Server error 500 came again when I try to create an account today.
