### ISSUE TITLE
import features fails

### ISSUE THREAD

**Issue by Charlotte0592** [tsattler/visuallocalizationbenchmark#60]
Thanks for sharing the amaing benchmark!
I have some promblems when I run: 
```
python reconstruction_pipeline_aachen_v1_1.py 
	--dataset_path /local/aachen 
	--colmap_path /local/colmap/build/src/exe
	--method_name method
```
then, it happens:
```
Traceback (most recent call last):
  File "reconstruction_pipeline_aachen_v1_1.py", line 335, in <module>
    import_features(images, paths, args)
  File "reconstruction_pipeline_aachen_v1_1.py", line 164, in import_features
    cursor.execute("INSERT INTO keypoints(image_id, rows, cols, data) VALUES(?, ?, ?, ?);",
sqlite3.IntegrityError: UNIQUE constraint failed: keypoints.image_id
```
Does it means there are two or more same keypoints?
Could please help me solve this problem?

**Comment by tsattler** [comment]
Can you provide more details on what you are trying to do? How do you obtain the features?

**Comment by Charlotte0592** [comment]
> Can you provide more details on what you are trying to do? How do you obtain the features?

According to [Aachen v1.1 dataset](https://www.visuallocalization.net/datasets/), I wrote a [images list]([images_list.txt](https://github.com/tsattler/visuallocalizationbenchmark/files/8753477/images_list.txt)) by myself and then used [extract.py in R2D2](https://github.com/naver/r2d2/blob/master/extract.py) to extract local features, using the following command:
```bash
${PYTHONBIN} extract.py --model my_models/${LOCAL}.pt --images ${DATASETS_PATH}/images_list.txt --min-scale 0.3 --min-size 0 --max-size 9999 --top-k ${KPTS} --tag ${METHOD}
```
And I want to check whether my algorithm to extract local features is work, so I run 
```bash
python reconstruction_pipeline_aachen_v1_1.py \
	--dataset_path ${DATASETS_PATH} \
	--colmap_path colmap \
	--method_name ${METHOD}
```
I want to use only local features to achieve visual localization, so I run this pipeline to obtain the queries' pose, in order to check whether my own algorithm is good.
But I ran into the problem as described above. Could you please give some advice?

**Comment by Charlotte0592** [comment]
According to [Aachen v1.1 dataset](https://www.visuallocalization.net/datasets/), I wrote a [images_list.TXT](https://github.com/tsattler/visuallocalizationbenchmark/files/8753634/images_list.TXT) by myself and then used [extract.py in R2D2](https://github.com/naver/r2d2/blob/master/extract.py) to extract local features, using the following command:
```bash
${PYTHONBIN} extract.py --model my_models/${LOCAL}.pt --images ${DATASETS_PATH}/images_list.txt --min-scale 0.3 --min-size 0 --max-size 9999 --top-k ${KPTS} --tag ${METHOD}
```
And I want to check whether my algorithm to extract local features is work, so I run 
```bash
python reconstruction_pipeline_aachen_v1_1.py \
	--dataset_path ${DATASETS_PATH} \
	--colmap_path colmap \
	--method_name ${METHOD}
```
I want to use only local features to achieve visual localization, so I run this pipeline to obtain the queries' pose, in order to check whether my own algorithm is good.
But I ran into the problem as described above. Could you please give some advice?

**Comment by tsattler** [comment]
The error `sqlite3.IntegrityError: UNIQUE constraint failed: keypoints.image_id` indicates that there are two images with the same image_id. I haven't seen this happening before though. Did you change anything else?
