### ISSUE TITLE
Qustion about the benchmark ranking rules

### ISSUE THREAD

**Issue by Vincentqyw** [tsattler/visuallocalizationbenchmark#61]
I am so confused about the ranking rules or the sorting methods of the benchmark, could you please help me solve this?

**Comment by tsattler** [comment]
Sure, happy to help. Do you have a concrete question?

**Comment by Vincentqyw** [comment]
My question is what's the ranking rule of the benchmark.

<img width="1217" alt="image" src="https://user-images.githubusercontent.com/18531182/171114839-828339c6-aef4-420e-82d9-46567999646e.png">

e.g. I have compared the sum of each (row) reported result, the sum of `OSpace`  is larger than `Megloc` yet the method `Megloc` rank 1st and `OSpace` 2nd.

<img width="1036" alt="image" src="https://user-images.githubusercontent.com/18531182/171122018-aa3c273f-1151-404d-be0a-034086b79519.png">

**Comment by tsattler** [comment]
We use the Schulze method (https://en.wikipedia.org/wiki/Schulze_method) to rank entries. If I remember correctly, we use the sum / average to break ties (but I am not sure anymore).

**Comment by Vincentqyw** [comment]
Got it, thanks for your help.
