### ISSUE TITLE
Unable to register 

### ISSUE THREAD

**Issue by SunghwanHong** [tsattler/visuallocalizationbenchmark#62]
Hello,
I was trying to sign up for https://www.visuallocalization.net/ 
But then i've been getting this "Server Error (500)".

Any solution to this? 
Thanks!

**Comment by kunalchelani** [comment]
Hi @SunghwanHong.

Yes, there seems to be an issue with the signup. I am currently responsible for maintaining the server. I tried debugging the issue today but there wasn't something obvious that came up. Unfortunately, I have limited bandwidth for this task, but I will try to resolve it as soon as possible and post an update here once resolved.

Meanwhile, thanks for your patience.

**Comment by cfiore-jpg** [comment]
I am still experiencing the same error as Sunghwan. I see this issue is almost a month old. Are there any updates on this?

**Comment by tsattler** [comment]
@kunalchelani Can you please look into this?

**Comment by SunghwanHong** [comment]
@kunalchelani still waiting..

**Comment by kunalchelani** [comment]
Hi @SunghwanHong ! Update: Our server uses a Gmail account to send activation emails. Gmail recently updated its security settings which resulted in an error in sending emails. 
While we figure a solution/replacement, I have removed the step of email based authentication and you should be able to signup successfully and use all services. Please reply here if certain issues persist. Thanks for the patience.

**Comment by SunghwanHong** [comment]
It works! 
Thanks.
