### ISSUE TITLE
Couldn't Open the URL： 502 Bad Gateway

### ISSUE THREAD

**Issue by Charlotte0592** [tsattler/visuallocalizationbenchmark#63]
Thanks for your great work!
But, excuse me. When I tried to open the URL [http://visuallocalization.net/](http://visuallocalization.net/), it got 502 Bad Gateway error. 
Doesn't this website open anymore?

**Comment by tsattler** [comment]
We are looking into it, thank you very much for reporting.

**Comment by kunalchelani** [comment]
The server seems to be up now. It can be closed for now.

**Comment by hmf21** [comment]
Hi, @kunalchelani 
Is there any solutions or alternative repositories about DenseVLAD? it seems still the unavailable and broken link at present.

**Comment by tsattler** [comment]
Please see #58
