### ISSUE TITLE
Evaluation server may be down

### ISSUE THREAD

**Issue by lmz-whu** [tsattler/visuallocalizationbenchmark#64]
Hello,
I have stayed "Scheduled for processing" status for two days.
Is this normal?
Thanks.

![image](https://user-images.githubusercontent.com/29139772/175753269-85164e25-daab-4a8c-9987-58a9ff2de533.png)

**Comment by tsattler** [comment]
We are looking into it, thanks for letting us know.

**Comment by lmz-whu** [comment]
The problem has been solved. Thanks!
