### ISSUE TITLE
Where are the descriptors added ?

### ISSUE THREAD

**Issue by alexs7** [tsattler/visuallocalizationbenchmark#65]
https://github.com/tsattler/visuallocalizationbenchmark/blob/1f8e4311e6fc41519e3d9909e14fce9a7f013732/local_feature_evaluation/modify_database_with_custom_features_and_matches.py#L79

I was looking at this code, and I can't understand how the descriptors are added ?

**Comment by tsattler** [comment]
The descriptors are **not** stored in the database. Colmap's database format only supports 128D descriptors and does not support any other lengths. We thus store the keypoints with dummy descriptors, do the matching outside of Colmap, and then import the matches for further processing.
