### ISSUE TITLE
the server does not produce any results

### ISSUE THREAD

**Issue by aigerd** [tsattler/visuallocalizationbenchmark#66]
scheduling is set but no results are produced.
this happens on all datasets, starting from 11/2/2023.
it was fine before.

**Comment by tsattler** [comment]
Thanks for letting us know. We will look into it.

**Comment by kunalchelani** [comment]
The university server seems to have some issues at the moment. We are working to getting it up soon. Thanks for the patience!

**Comment by aigerd** [comment]
thanks. do you have time estimation? i need this for iccv submission coming
soon.
is there some other way to do it, e.g. sharing the actual code that does
this and/or GT?

**Comment by tsattler** [comment]
We hope to have everything running again by the end of the week.

**Comment by tsattler** [comment]
Should be fixed now.
