### ISSUE TITLE
evaluation code

### ISSUE THREAD

**Issue by xiaoxiaoczw** [tsattler/visuallocalizationbenchmark#68]
Hi, 

Thank you for your outstanding work! 
Would you mind sharing the evaluation code (the part calculate (0.25m, 2°) / (0.5m, 5°) / (5m, 10°))? In this way, I can use the same evaluation metrics as yours to evaluate custom datasets. 

Thanks!

**Comment by tsattler** [comment]
The code is fairly trivial: For each query image, you compute the rotation and position error with respect to the ground truth pose (see the paper for the precise definition). You then compute the percentage of queries for which the rotation error is below 2 degrees and the position error is below 25cm, etc.
You can also have a look at this repository: https://github.com/tsattler/visloc_pseudo_gt_limitations
