### ISSUE TITLE
RobotCar Seasons's image format

### ISSUE THREAD

**Issue by zhuixunforever** [tsattler/visuallocalizationbenchmark#7]
the image in floder 'images/' is 'xxx.jpg', but the image's name of the file xxx.nvm in 3D-models/all-merged and 3D-models/individual is 'xxx.png'. It's need us to convert the 'xxx.jpg' in the 'images/' to 'xxx.png'.
Thank you for your nice work!

**Comment by tsattler** [comment]
@zhuixunforever No need to convert the images. The poses are the same, i.e., "xxx.png" and "xxx.jpg" have exactly the same extrinsic and intrinsic parameters. We chose to share jpg images rather than png images due to their file size.

**Comment by zhuixunforever** [comment]
@tsattler thank you for your reply, and I will change the image's name of the xxx.nvm to 'xxx.jpg'
