### ISSUE TITLE
About InLoc result 0.0 / 0.0 / 0.0

### ISSUE THREAD

**Issue by morankim** [tsattler/visuallocalizationbenchmark#70]
Hi, I submitted result like this. 
"IMG_1031.JPG 0.5453042984 -0.8026322126 -0.208494544 0.1222897917 9.65199852 -8.090942383 2.480159283"
but the server gives 0.0 / 0.0 / 0.0
so I scaled it like "IMG_1031.JPG 0.5453042984 -0.8026322126 -0.208494544 0.1222897843 680.833252 -570.7194214 174.9456329" but it gives the same result. 
can you tell me what is wrong? 

I used global DUC alignment transformation to transform the scan points(originally from ptx) to world points(=floor points). 
Then I transformed this world points to camera points using floor-to-camera transformation using P_db() function. 
([InLoc_demo](https://github.com/HajimeTaira/InLoc_demo/tree/master/functions/wustl_function)
/P_db.m)

**Comment by tsattler** [comment]
Are you sure you are using the right format?

**Comment by morankim** [comment]
I found error. It was my mistake. Thank you.
