### ISSUE TITLE
Adapting the code to RobotCar

### ISSUE THREAD

**Issue by uzpaka** [tsattler/visuallocalizationbenchmark#9]
Hello,

I have tried to adapt the given code used for the Aachen dataset to the RobotCar dataset. For each query image, I find the 20 nearest reference images using NetVLAD, match the query image to these 20 reference images, and exhaustively match the 20 reference images between each other. For the matching, D2-net features were used.

Given the reference poses (/3D-models/all-merged/all.nvm), camera intrinsics (/intrinsics), and an empty COLMAP database that I created on my own (which is consistent with the Aachen files), I was able to run the reconstruction_pipeline.py script. Everything seems to work until the 'point_triangulator' function, which produces no output (and therefore the subsequent calls to 'image_registrator' and 'model_converter' fail). 

What could be the reason for the 'point_triangulator' to fail and produce no output model? The terminal shows no error or warnings. Is it because of the intrinsics I used (as mentioned in this issue https://github.com/tsattler/visuallocalizationbenchmark/issues/2)? Or because of the matching?

**Comment by tsattler** [comment]
There are a couple of things that could go wrong:
1) Did you verify that you get relevant images during image retrieval? Especially, do you get multiple images of the same place as the query (which you would need to triangulate the scene)?
2) Do the feature matches that you import seem correct? You can have a look at the through the colmap gui.
3) Another common cause for the point_triangulator failing to produce a 3D model is that there are some errors in the poses that it reads as input. Are you following colmap's file format? Did you load the "empty" reconstruction (containing only the poses of the database images) in the colmap gui and do the results look meaningful?

#2 should not be an issue here.

**Comment by uzpaka** [comment]
Thanks for the detailed answer!

1. In general, the closest reference images match the query quite well. But it is not always correct, sometimes only the 10 closest images actually overlap with the query, sometimes more or less. For difficult conditions (night), the image retrieval is bad. Therefore the matching is also affected, and I am not sure how COLMAP deals with such inconsistent cases (since we are trying to match images with quite different poses). 

However, I was able to achieve a decent baseline on the Aachen Day-Night queries, with the same methodology/code, using NetVLAD to get the 20 closest reference images (and not using the given matching pairs of course), and D2-Net features (single-scale) for the matching. I assume that the image retrieval there is also not perfect, but the point_triangulator function was still able to output a model.

2. I will verify them but they should be correct because my code worked for Aachen already. Maybe I should use multi-scale D2-Net features (instead of single-scale) to get better matching, but I doubt that it will make a difference because in RobotCar the query and reference images were taken with the same camera and approximately at the same locations.

3. I loaded the empty model in COLMAP and it looked good:
The entire map:
![global](https://user-images.githubusercontent.com/43315025/70044037-d4b93380-15c1-11ea-88ce-5b4258e06c0f.png)
And when I zoom in I can see the 3 cameras (left,rear,right):
![zoomed](https://user-images.githubusercontent.com/43315025/70044049-da167e00-15c1-11ea-934e-ebce2b9949d9.png)

This would suggest that the reference poses are correct.

I am basically trying to reproduce this baseline https://www.visuallocalization.net/details/889/. The only difference I see is that I used NetVLAD instead of DenseVLAD, and that they considered 'rear' images only (not sure what that means exactly).

**Comment by tsattler** [comment]
Indeed the map looks good.

If COLMAP does not have enough matches, it will not triangulate points. There is no problem if there are some cameras that do not generate 3D points. They will just be ignored.
Can you verify whether you get any 3D points triangulated?

For the baseline you mentioned, we first triangulated the full model using D2-Net and the known poses of the database images. For evaluation, we only considered the rear images (as only those are actually evaluated by the service) and performed retrieval of the rear test images against the rear database images. After matching, we ran the point_triangulator using the full database model we had constructed before, i.e., we did not compute multiple small reconstructions.

**Comment by uzpaka** [comment]
I actually do not get any 3D points triangulated after calling COLMAP's point_triangulator. The call simply shows this:

```
Loading cameras... 32796 in 0.053s
Loading matches... 928755 in 16.839s
Loading images... 32796 in 5.982s (connected 26661)
Building correspondence graph...
```

I think my problem is that I do not do as many matchings as you do. The matchings I do are similar to the ones for Aachen (as can be seen from the given 'image_pairs_to_match.txt' file). How exactly did you triangulate the full model using D2-Net, i.e how did you generate the matching pairs between the reference images for this? From what I understood, this is a quite different approach than the one used for the Aachen dataset in this repository, because the triangulation is done from an empty model.

**Comment by tsattler** [comment]
I think we computed for each database images all other database images within 5 or 10 meters whose orientation did not differ by too much (up to 45 degree or so) and then matched these pairs in order to triangulate the point cloud.

Does COLMAP directly finish after the output you showed? Because "Building correspondence graph..." just means that it is currently building it, which can take quite some time.

**Comment by uzpaka** [comment]
Yes the call returns after "Building correspondence graph...". 

Thank you for the details! I will then first create a 3D model of the city before registering the query images.

**Comment by tsattler** [comment]
Hm.. it should give some more output (with timing). Does it crash or just return?

**Comment by uzpaka** [comment]
My bad, you are actually right and I feel deceived by Python! The colmap
point_triangulator command was launched using Python's 'subprocess' module,
as used in the 'reconstruction_pipeline.py' script. But when I launched the
command on the terminal, I could see that the process was killed due to
lack of free memory most likely. This was not reported by Python (the
colmap command simply returns and Python continues running the script), so
I thought that colmap was the issue. As I am new to colmap, I also didn't
know the expected output of that command in case of failed or weak matches.

I have freed enough memory and the triangulation is now running! Thanks
again for your help. Also, it will be interesting to see if there will be a
significant difference in accuracy with my approach for matching the
queries versus your approach.

**Comment by maximilianmuehlbauer** [comment]
Hi @uzpaka, did your original approach show success or have you already switched to what @tsattler  has implemented? I try to implement the same pipeline (matching 20 nearest neighbors among each other and to the query image) but from inspecting a few samples the triangulation performance doesn't seem to be too good. Images seem to be registered pretty far from where their nearest neighbors are, some even far from the entire scene. Did you get better results not triangulating the full reconstruction?

What would good error values for colmap bundle adjustment be? I get a cost around 1-2e5 or 1px - that is probably too high I guess?

**Comment by uzpaka** [comment]
Hi @maximilianmuehlbauer, yes the original approach worked and the results were just a bit lower than their approach. The additional differences are that I used NetVLAD instead of DenseVLAD and that I considered all 3 types of cameras instead of just the 'rear' one. I am not sure if considering all the cameras help to improve the results or not. It seems that COLMAP is dealing fine when given a pair of images to match that actually do not overlap. 

As for the bundle adjustment, I do not know the 'good' values for the cost. I remember that the BA took quite a while to converge, and that it required 64GB of memory (when reconstructing the entire database with the 3 cameras).

**Comment by maximilianmuehlbauer** [comment]
Hello @uzpaka, then I must have a grave error somewhere...

Would you be happy to share your code? Please don't hesitate to contact me via the email you find on my profile if that's possible for you!

**Comment by uzpaka** [comment]
Hi @maximilianmuehlbauer, here it is. The python script is basically the same as the 'reconstruction_pipeline.py' file of this repository and should be used in the same way. You will need to adapt the paths in the main function. Also you will find a new empty COLMAP database that I created from scratch using python scripts that can be found in the COLMAP repository. In fact, the given COLMAP database for RobotCar had inconsistent names (.png instead of .jpg) as well as SIFT detections/matches, which is not necessary. I also put a text file of the matches found by NetVLAD.
The reconstruction takes a fair amount of memory and time, you might want to remove the non-rear images from the database and the matching file to speed it up. 

[reconstruction_pipeline_robotcar.zip](https://github.com/tsattler/visuallocalizationbenchmark/files/3974088/reconstruction_pipeline_robotcar.zip)

**Comment by Huang-NienPei** [comment]
> Hi @maximilianmuehlbauer, here it is. The python script is basically the same as the 'reconstruction_pipeline.py' file of this repository and should be used in the same way. You will need to adapt the paths in the main function. Also you will find a new empty COLMAP database that I created from scratch using python scripts that can be found in the COLMAP repository. In fact, the given COLMAP database for RobotCar had inconsistent names (.png instead of .jpg) as well as SIFT detections/matches, which is not necessary. I also put a text file of the matches found by NetVLAD. The reconstruction takes a fair amount of memory and time, you might want to remove the non-rear images from the database and the matching file to speed it up.
> 
> [reconstruction_pipeline_robotcar.zip](https://github.com/tsattler/visuallocalizationbenchmark/files/3974088/reconstruction_pipeline_robotcar.zip)

When I use lf-net for positioning experiments, when I run to BA, the following error will occur, and the files in the sparse-lf-net-database cannot be generated correctly. I still don’t know where the problem is, how can I fix this wrong. I want to ask you.

![problem](https://user-images.githubusercontent.com/53600867/135801302-7b3e22ef-0100-4c63-b89d-e7abe087119b.jpeg)

Looking forward to your reply, thank you.

**Comment by tsattler** [comment]
As the error says, Colmap is unable to find the reconstruction files (cameras.txt, images.txt and points3D.txt respectively cameras.bin, images.bin, points3D.bin) at the corresponding directory. Please make sure to point to the directory that contains these files.

**Comment by Huang-NienPei** [comment]
The reason why these three files cannot be generated correctly may be that the Bundle adjustment cannot be run.
I observed that the iteration only runs once and then ends, as shown in the figure.
Could it be because the Bundle adjustment cannot converge? How should I solve this problem?

![3221633334793_ pic_hd](https://user-images.githubusercontent.com/53600867/135817823-324e5ecf-8ee9-4983-b2d2-6f5ac151a113.jpg)

**Comment by Huang-NienPei** [comment]
> As the error says, Colmap is unable to find the reconstruction files (cameras.txt, images.txt and points3D.txt respectively cameras.bin, images.bin, points3D.bin) at the corresponding directory. Please make sure to point to the directory that contains these files.

The reason why these three files cannot be generated correctly may be that the Bundle adjustment cannot be run.
I observed that the iteration only runs once and then ends, as shown in the figure.
Could it be because the Bundle adjustment cannot converge? How should I solve this problem?

![3221633334793_ pic_hd](https://user-images.githubusercontent.com/53600867/135817945-89bf483c-3d69-40d6-9e32-8210bca49350.jpg)

**Comment by tsattler** [comment]
Do you see a crash during the bundle adjustment? That is not obvious to me from the screenshot.

You will need quite a bit of memory for the bundle adjustment for the RobotCar dataset. If things crash, please check whether you are running out of RAM.
